version: '2'
services:
  influxdb:
    image: influxdb:1.7-alpine
    environment:
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
      - INFLUXDB_USER=ecowitt
      - INFLUXDB_USER_PASSWORD=ecowitt
      - INFLUXDB_DB=weather
    volumes:
      - ./influxdb:/var/lib/influxdb
    ports:
      - 8086:8086
  ecowittinfluxdb:
    build: .
    environment:
      - INFLUXDB_ADDRESS=http://influxdb:8086
      - INFLUXDB_USER=ecowitt
      - INFLUXDB_PASSWORD=ecowitt
      - INFLUXDB_DATABASE=weather
    ports:
      - 4242:4242
